remote_theme: hacker
name: alex.dance
title: null
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - energy.md
permalink: /posts/
